version: '3.8'

services:
  app:
    container_name: my-java-app
    #    image: fru2zzy/my-java-app:latest
    build: ./app

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/test
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    #    image: fru2zzy/docker_postgres
    build: ./postgres

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: